import enum

W_PREV = 40
W_SUB = 10
W_AGG = 10
MAX_TOKENS_THREAD_DECISION = 8
TEMP_THREAD_DECISION = 0.0
MAX_TOKENS_THREAD_SUMMARY = 100
TEMP_THREAD_SUMMARY = 0.1
N_ACTIVE_THREADS = 3
N_ATTEMPTS = 5
N_LAST_MESSAGES_IN_THREAD = 5
N_LAST_MESSAGES_FOR_SUMMARY = 5
N_RECENT_MESSAGES = 20
BATCH_SIZE_DIALOGUE_DISENTANGLEMENT = 20
MAX_WORDS_QUICK_REPLY = 3
MAX_SECONDS_QUICK_REPLY = 60 * 60
DIALOGUE_DISENTANGLEMENT_TEMPLATE = 'llm/prompts/thread_decision.jinja2'
THREAD_SUMMARY_TEMPLATE = 'llm/prompts/thread_summary.jinja2'


class AvailableModel(enum.StrEnum):
    QWEN_3_5_9B = "QWEN_3_5_9B"
