W_PREV = 40
W_SUB = 10
W_AGG = 10
N_ACTIVE_THREADS = 4
N_ATTEMPTS = 5
N_LAST_MESSAGES_IN_THREAD = 5
BATCH_SIZE_DIALOGUE_DISENTANGLEMENT = 100
DIALOGUE_DISENTANGLEMENT_TEMPLATE = 'llm/prompts/thread_decision.jinja2'
