import enum

W_PREV = 40
W_SUB = 10
W_AGG = 10
MAX_TOKENS_THREAD_DECISION = 8
TEMP_THREAD_DECISION = 0.0
N_ACTIVE_THREADS = 3
N_ATTEMPTS = 5
N_LAST_MESSAGES_IN_THREAD = 5
N_RECENT_MESSAGES = 20
BATCH_SIZE_DIALOGUE_DISENTANGLEMENT = 20
DIALOGUE_DISENTANGLEMENT_TEMPLATE = 'llm/prompts/thread_decision.jinja2'


class AvailableModel(enum.StrEnum):
    QWEN_3_5_9B = "QWEN_3_5_9B"
