version: "3.9"

services:
  postgres:
    image: postgres:16.3
    container_name: neuroclone_postgres
    restart: always
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: neuroclone_dev
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13.7-management-alpine
    container_name: neuroclone_rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro

  redis:
    image: redis:7.4-alpine
    container_name: neuroclone_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
