[project]
name = "neuroclonemodel"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "io-23SklyarAnton", email = "80kap.i.toshka@gmail.com" }
]
dependencies = [
    "mlx-lm>=0.31.2",
    "pydantic>=2.13.3",
    "jinja2>=3.1.6",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "aiogram>=3.28.2",
    "dishka>=1.10.1",
    "sqlalchemy>=2.0.49",
    "psycopg2-binary>=2.9.12",
    "celery>=5.6.3",
    "redis>=8.0.0",
]
readme = "README.md"
requires-python = ">=  3.12.7"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/neuroclonemodel"]

[tool.rye.scripts]
infra-up = "docker compose up -d"
infra-down = "docker compose down"

bot = { cmd = "python src/app.py", env-file = ".env" }

worker-cpu = { cmd = "celery -A infrastructure.celery.celery_app --workdir=src worker --pool=prefork --concurrency=4 --queues=celery --loglevel=info", env-file = ".env" }
worker-ml = { cmd = "celery -A infrastructure.celery.celery_app --workdir=src worker --pool=solo --queues=ml --loglevel=info", env-file = ".env" }

beat = { cmd = "celery -A infrastructure.celery.celery_app --workdir=src beat --loglevel=info", env-file = ".env" }

start-all = "sh -c 'trap \"kill 0\" EXIT INT TERM; rye run bot & rye run worker-cpu & rye run worker-ml & rye run beat & wait'"

trigger = { cmd = "python src/scripts/trigger.py", env-file = ".env" }
reset = { cmd = "python src/scripts/reset.py", env-file = ".env" }
